package com.yb.icgapi.icpic.infrastructure.api.aliYunAi.model;

import cn.hutool.core.annotation.Alias;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;

import java.io.Serializable;

/**
 * 图像扩图API请求实体类
 */
@Data
public class CreateOutPaintingTaskRequest implements Serializable {

    /**
     * 模型名称 (必选)
     * 示例值: image-out-painting
     */
    @Alias("model")
    private String model = "image-out-painting";

    /**
     * 输入图像的基本信息 (必选)
     */
    @Alias("input")
    private Input input;

    /**
     * 输出图像的处理参数 (必选)
     */
    @Alias("parameters")
    private Parameters parameters;


    /**
     * 输入图像信息
     */
    @Data
    public static class Input {

        /**
         * 图像URL地址或者图像base64数据 (必选)
         */
        @Alias("image_url")
        private String imageUrl;

    }

    /**
     * 图像处理参数
     */
    @Data
    public static class Parameters {

        /**
         * 逆时针旋转角度 (可选)
         * 默认值: 0, 取值范围: [0, 359]
         */
        @Alias("angle")
        private Integer angle;

        /**
         * 图像宽高比 (可选)
         * 可选值: ["","1:1", "3:4", "4:3", "9:16", "16:9"]
         */
        @Alias("output_ratio")
        private String outputRatio;

        /**
         * 水平方向扩展比例 (可选)
         * 默认值: 1.0, 取值范围: [1.0, 3.0]
         */
        @Alias("x_scale")
        @JsonProperty("xScale")
        private Float xScale;

        /**
         * 垂直方向扩展比例 (可选)
         * 默认值: 1.0, 取值范围: [1.0, 3.0]
         */
        @Alias("y_scale")
        @JsonProperty("yScale")
        private Float yScale;

        /**
         * 在图像上方添加像素 (可选)
         * 默认值: 0
         */
        @Alias("top_offset")
        private Integer topOffset;

        /**
         * 在图像下方添加像素 (可选)
         * 默认值: 0
         */
        @Alias("bottom_offset")
        private Integer bottomOffset;

        /**
         * 在图像左侧添加像素 (可选)
         * 默认值: 0
         */
        @Alias("left_offset")
        private Integer leftOffset;

        /**
         * 在图像右侧添加像素 (可选)
         * 默认值: 0
         */
        @Alias("right_offset")
        private Integer rightOffset;

        /**
         * 开启图像最佳质量模式 (可选)
         * 默认值: false
         */
        @Alias("best_quality")
        private Boolean bestQuality;

        /**
         * 限制模型生成的图像文件大小 (可选)
         * 默认值: true
         */
        @Alias("limit_image_size")
        private Boolean limitImageSize;

        /**
         * 添加Generated by AI水印 (可选)
         * 默认值: true
         */
        @Alias("add_watermark")
        private Boolean addWatermark;

    }
}