# 工作流名称
name: Deploy ICG API to Server

# 触发条件：当代码 push 到 main 分支时触发
on:
  push:
    branches: [ "main" ]

# 定义一系列任务
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Rename JAR file
        run: mv target/icg-api-0.0.1-SNAPSHOT.jar target/app.jar

      # 步驟5: 使用 rsync 部署文件並執行重啟命令
      - name: Deploy to Server using rsync
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i" # rsync 參數，-i 打印文件信息
          SOURCE: "target/app.jar" # 源文件
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
          REMOTE_PORT: ${{ secrets.SERVER_PORT || 22 }}
          TARGET: "/opt/icg/" # 目標目錄
          # 部署後執行的腳本
          SCRIPT_AFTER: "sudo systemctl restart icg.service"